// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "life0":return img`
. . f f . . . f f . . 
. f . . f . f . . f . 
f . . . . f . . . . f 
f . . . . . . . . . f 
f . . . . . . . . . f 
. f . . . . . . . f . 
. . f . . . . . f . . 
. . . f . . . f . . . 
. . . . f . f . . . . 
. . . . . f . . . . . 
`;
            case "image4":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . 5 5 5 . . . . . . . . . . 
. . . 5 . 5 5 5 5 5 5 . . . . . 
. . . 5 5 5 . . 5 . 5 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "sword":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbfff.f......
..........ffffffff......
............fffff.......
........................
........................
........................
........................
`;
            case "image5":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 6 . . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . . 6 6 6 . . . . . . . 
. . . . . 6 6 6 6 6 . . . . . . 
. . . . . . . e . . . . . . . . 
. . . . . . . e . . . . . . . . 
. . . . . . . 6 . . . . . . . . 
`;
            case "image1":
            case "life":return img`
. . f f . . . f f . . 
. f 2 2 f . f 2 2 f . 
f 2 2 1 2 f 2 2 2 2 f 
f 2 1 2 2 2 2 2 2 2 f 
f 2 2 2 2 2 2 2 2 2 f 
. f 2 2 2 2 2 2 2 f . 
. . f 2 2 2 2 2 f . . 
. . . f 2 2 2 f . . . 
. . . . f 2 f . . . . 
. . . . . f . . . . . 
`;
            case "image6":
            case "break":return img`
d111111bd111111bd111111bd111111bd111111bd111111bd111111bd111111b
1ddddddb1dddddbb1ddddddb1dddddbb1ddddddb1dddddbb1ddddddb1dddddbb
1ddddddb1ddddbdb1ddddddb1ddddbdb1ddddddb1ddddbdb1ddddddb1ddddbdb
1ddddddb1ddd11db1ddddddb1ddd11db1ddddddb1ddd11db1ddddddb1ddd11db
1ddddddb1ddbdddb1ddddddb1ddbdddb1ddddddb1ddbdddb1ddddddb1ddbdddb
1ddddddb1dbbdddb1ddddddb1dbbdddb1ddddddb1dbbdddb1ddddddb1dbbdddb
1ddddddd1dbbdddd1ddddddd1dbbdddd1ddddddd1dbbdddd1ddddddd1dbbdddd
bbbbbbdebbbbbbdebbbbbbdebbbbbbdebbbbbbdebbbbbbdebbbbbbdebbbbbbde
d111111bd111111bd111111bd111111bd111111bd111111bd111111bd111111b
1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb
1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb
1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb1ddddddb
1dddddbb1ddddddb1dddddbb1ddddddb1dddddbb1ddddddb1dddddbb1ddddddb
1ddddbbb1ddddddb1ddddbbb1ddddddb1ddddbbb1ddddddb1ddddbbb1ddddddb
1ddddbbd1ddddddd1ddddbbd1ddddddd1ddddbbd1ddddddd1ddddbbd1ddddddd
bbbbbbbebbbbbbbebbbbbbbebbbbbbbebbbbbbbebbbbbbbebbbbbbbebbbbbbbe
`;
            case "image8":
            case "myImage1":return img`
1 1 b b b b b b b b b b b b 1 1 
1 b e 4 4 4 4 4 4 4 4 4 4 e b 1 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b c c b b b b b b c 
c c c c c c b c c b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
1 b b 1 1 1 1 1 1 1 1 1 1 b b 1 
`;
            case "image9":
            case "myImage2":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . b b b b b b b b b b b b . . 
. . b 4 4 e e e e e e e e b . . 
. b 4 4 e e e e e e e e e b b . 
. 1 . 1 . 1 b b b b b b b e b . 
. . . . . . 1 b e e e e e e b . 
. 3 3 3 3 . . b e e e e e e b . 
. 1 c 3 3 3 1 b e e e e e e b . 
. b 1 c 1 3 b e e e e e e e b . 
. b e e e e e e e e e e e e b . 
. b b b b b b b b b b b b b b . 
. . b . . . . . . . . . . b . . 
`;
            case "image10":
            case "mimicchest":return img`
1 1 b b b b b b b b b b b b 1 1 
1 b e 4 4 4 4 4 4 4 4 4 4 e b 1 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b c c b b b b b b c 
c c c c c c b c c b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
1 b b 1 1 1 1 1 1 1 1 1 1 b b 1 
`;
            case "image7":
            case "break1":return img`
b b b b b b b e b b b b b b b e 
1 d d d d b b d 1 d d d d d d d 
1 d d d d b b b 1 d d d d d d b 
1 d d d d d b b 1 d d d d d d b 
1 d d d d d d b 1 d d d d d d b 
1 d d d d d d b 1 d d d d d d b 
1 d d d d d d b 1 d d d d d d b 
d 1 1 1 1 1 1 b d 1 1 1 1 1 1 b 
b b b b b b d e b b b b b b d e 
1 d d d d d d d 1 d b b d d d d 
1 d d d d d d b 1 d b b d d d b 
1 d d d d d d b 1 d d b d d d b 
1 d d d d d d b 1 d d d 1 1 d b 
1 d d d d d d b 1 d d d d b d b 
1 d d d d d d b 1 d d d d d b b 
d 1 1 1 1 1 1 b d 1 1 1 1 1 1 b 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "skellydestroy":
            case "anim2":return [img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbfff.f......
..........ffffffff......
............fffff.......
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111bf........
........ff1b1bff........
.........fbfbff.........
..........fffff.........
............ff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc111b.........
........ff1b1bf.........
.........fbfbf..........
..........f.f...........
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f1111111df.......
......fd1111111ddf......
......fd111111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......ff111111df.......
......fdff11111ddf......
......fd1ff111dddf......
......fd111ddddddf......
......fd1dfbddddbf......
......fbddfcdbbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......ff111111df.......
......fdff11111ddf......
......fd1ff111dddf......
......fd11ffdddddf......
......fd1dfffdddbf......
......fbddfcffbbcf......
.......f11111bbcf.......
.......f1b1fffff........
.......fbfc.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
...........ffff.........
.........ff1111ff.......
........fb111111bf......
..........111111df......
...........11111ddf.....
.......ff...111dddf.....
......fdff...dddddf.....
......fd1ff77.dddbf.....
......fd11ff7..bbcf.....
......fd1dfff7..cf......
......fbddfcff..f.......
.......f11111ff.........
.......f1b1ffff.........
.......fbfc.............
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
................ffff....
..............ff1111ff..
.............fb111111bf.
...............111111df.
................11111ddf
.................111dddf
..................dddddf
...................dddbf
....................bbcf
...........77........cf.
..........7777.......f..
...........777..........
..ff.......777..........
.fdff.......7...........
.fd1ff..................
.fd11ff.................
.fd1dfff................
.fbddfcff...............
..f11111ff..............
..f1b1ffff..............
..fbfc..................
........................
`, img`
........................
........................
................ffff....
..............ff1111ff..
........7....fb111111bf.
........7......111111df.
........77......11111ddf
.........77......111dddf
..........7.......dddddf
..........7........dddbf
..........7.........bbcf
..........777........cf.
..........7777.......f..
...........777..........
..ff.......777..........
.fdff.......7...........
.fd1ff..................
.fd11ff.................
.fd1dfff................
.fbddfcff...............
..f11111ff..............
..f1b1ffff..............
..fbfc..................
........................
`, img`
......7.................
......77................
.......7........ffff....
.......7......ff1111ff..
.......77....fb111111bf.
........7......111111df.
........77......11111ddf
.........77......111dddf
..........7.......dddddf
..........7........dddbf
..........7.........bbcf
..........77.........cf.
..........7..........f..
........................
..ff....................
.fdff...................
.fd1ff..................
.fd11ff.................
.fd1dfff................
.fbddfcff...............
..f11111ff..............
..f1b1ffff..............
..fbfc..................
........................
`, img`
......7.................
......77................
.......7........ffff....
.......7......ff1111ff..
.......77....fb111111bf.
...............111111df.
................11111ddf
.................111dddf
..................dddddf
...................dddbf
....................bbcf
.....................cf.
.....................f..
........................
..ff....................
.fdff...................
.fd1ff..................
.fd11ff.................
.fd1dfff................
.fbddfcff...............
..f11111ff..............
..f1b1ffff..............
..fbfc..................
........................
`, img`
........................
........................
................ffff....
..............ff1111ff..
.............fb111111bf.
...............111111df.
................11111ddf
.................111dddf
..................dddddf
...................dddbf
....................bbcf
.....................cf.
.....................f..
........................
..ff....................
.fdff...................
.fd1ff..................
.fd11ff.................
.fd1dfff................
.fbddfcff...............
..f11111ff..............
..f1b1ffff..............
..fbfc..................
........................
`];
            case "walkmimic":
            case "anim4":return [img`
....................
....................
....................
....................
....................
..bbbbbbbbbbbb......
..b44eeeeeeeeb......
.b44eeeeeeeeebb.....
.1.1.1bbbbbbbeb.....
......1beeeeeeb.....
.3333..beeeeeeb.....
.1c3331beeeeeeb.....
.b1c13beeeeeeeb.....
.beeeeeeeeeeeeb.....
.bbbbbbbbbbbbbb.....
..b..........b......
`, img`
....................
....................
....................
....................
....................
...bbbbbbbbbbbbbb...
...b44eeeeeeeeeeb...
..b44eeeeeeeeeeebb..
..1.1.11bbbbbbbbeb..
........1beeeeeeeb..
..3333...beeeeeeeb..
..1c33331beeeeeeeb..
..b1c133beeeeeeeeb..
..beeeeeeeeeeeeeeb..
..bbbbbbbbbbbbbbbb..
...b............b...
`, img`
....................
....................
....................
..bbbbbbbbbbbb......
..b44eeeeeeeeb......
.b44eeeeeeeeebb.....
.1.1.1bbbbbbbeb.....
......beeeeeeeb.....
.......beeeeeeb.....
......1beeeeeeb.....
.3333..beeeeeeb.....
.1c3331beeeeeeb.....
.b1c13beeeeeeeb.....
.beeeeeeeeeeeeb.....
.bbbbbbbbbbbbbb.....
..b..........b......
`];
            case "myAnim1":
            case "anim5":return [img`
1 1 b b b b b b b b b b b b 1 1 
1 b e 4 4 4 4 4 4 4 4 4 4 e b 1 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b c c b b b b b b c 
c c c c c c b c c b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
1 b b 1 1 1 1 1 1 1 1 1 1 b b 1 
`];
            case "deathmimic":
            case "anim7":return [img`
....................
....................
....................
....................
....................
.......bbbbbbbbbbbb.
.......b44eeeeeeeeb.
......b44eeeeeeeeebb
......1.1.1bbbbbbbeb
...........1beeeeeeb
......3333..beeeeeeb
......1c3331beeeeeeb
......b1c13beeeeeeeb
......beeeeeeeeeeeeb
......bbbbbbbbbbbbbb
.......b..........b.
`, img`
....................
....................
....................
....................
....................
....................
.......bbbbbbbbbbbb.
.......b44eeeeeeeeb.
......b44eeeeeeeeebb
...........bbbbbbbeb
.....33333..beeeeeeb
.....31c3331beeeeeeb
......b1c13beeeeeeeb
......beeeeeeeeeeeeb
......bbbbbbbbbbbbbb
.......b..........b.
`, img`
....................
....................
....................
....................
....................
....................
....................
.......bbbbbbbbbbbb.
.......b44eeeeeeeeb.
......b44eeeeeeeeebb
.....33333.bbbbbbbeb
.....31c3331beeeeeeb
.....3b1c13beeeeeeeb
.....3beeeeeeeeeeeeb
......bbbbbbbbbbbbbb
.......b..........b.
`, img`
....................
....................
....................
....................
....................
....................
....................
.......bbbbbbbbbbbb.
.......b44eeeeeeeeb.
......b44eeeeeeeeebb
.....33333.bbbbbbbeb
.....31c3331beeeeeeb
.....3b1c13beeeeeeeb
.....3beeeeeeeeeeeeb
.....3bbbbbbbbbbbbbb
...333.b..........b.
`];
            case "bitemimic":
            case "anim6":return [img`
....................
....................
....................
....................
....................
.......bbbbbbbbbbbb.
.......b44eeeeeeeeb.
......b44eeeeeeeeebb
......1.1.1bbbbbbbeb
...........1beeeeeeb
......3333..beeeeeeb
......1c3331beeeeeeb
......b1c13beeeeeeeb
......beeeeeeeeeeeeb
......bbbbbbbbbbbbbb
.......b..........b.
`, img`
....................
....................
....................
.......bbbbbbbbbbbb.
.......b44eeeeeeeeb.
......b44eeeeeeeeebb
......1.1.1bbbbbbbeb
...........1beeeeeeb
............beeeeeeb
............beeeeeeb
......3333..beeeeeeb
......1c3331beeeeeeb
......b1c13beeeeeeeb
......beeeeeeeeeeeeb
......bbbbbbbbbbbbbb
.......b..........b.
`, img`
....................
....................
....................
....bbbbbbbbbbbbbbb.
....b44eeeeeeeeeeeb.
...b44eeeeeeeeeeeebb
...1.1.1bbbbbbbbbbeb
........1bbeeeeeeeeb
.........1.beeeeeeeb
............beeeeeeb
...3333..1.beeeeeeeb
...1c3331bbeeeeeeeeb
...b1c13beeeeeeeeeeb
...beeeeeeeeeeeeeeeb
...bbbbbbbbbbbbbbbbb
....b.............b.
`, img`
....................
....................
....................
....................
....................
....................
....bbbbbbbbbbbbbbb.
....b44eeeeeeeeeeeb.
...b44eeeeeeeeeeeebb
...1.1.1bbbbbbbbbbeb
...3333..1.beeeeeeeb
...1c3331bbeeeeeeeeb
...b1c13beeeeeeeeeeb
...beeeeeeeeeeeeeeeb
...bbbbbbbbbbbbbbbbb
....b.............b.
`];
            case "myAnim0":
            case "anim3":return [img`
1 1 b b b b b b b b b b b b 1 1 
1 b e 4 4 4 4 4 4 4 4 4 4 e b 1 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b f f b b b b b b c 
c c c c c c b f f b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
1 b b 1 1 1 1 1 1 1 1 1 1 b b 1 
`, img`
1 1 b b b b b b b b b b b b 1 1 
1 b e 4 4 4 4 4 4 4 4 4 4 e b 1 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b f f b b b b b b c 
c c c c c c b f f b c c c c c c 
c c c c c c c b b c c c c c c c 
b e e e e e c 3 3 c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
1 b b 1 1 1 1 1 1 1 1 1 1 b b 1 
`, img`
1 1 b b b b b b b b b b b b 1 1 
1 b e 4 4 4 4 4 4 4 4 4 4 e b 1 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b f f b b b b b b c 
c c c c c c b f f b c c c c c c 
c c c c c c c b b c c c c c c c 
c c c c c c c c c c c c c c c c 
c c c c c c 3 3 3 3 c c c c c c 
b e e e e e c 3 3 c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
1 b b 1 1 1 1 1 1 1 1 1 1 b b 1 
`];
            case "walkmimic0":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . b b b b b b b b b b b b . . 
. . b 4 4 e e e e e e e e b . . 
. b 4 4 e e e e e e e e e b b . 
. 1 . 1 . 1 b b b b b b b e b . 
. . . . . . 1 b e e e e e e b . 
. 3 3 3 3 . . b e e e e e e b . 
. 1 c 3 3 3 1 b e e e e e e b . 
. b 1 c 1 3 b e e e e e e e b . 
. b e e e e e e e e e e e e b . 
. b b b b b b b b b b b b b b . 
. . b . . . . . . . . . . b . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . b b b b b b b b b b b b . . 
. . b 4 4 e e e e e e e e b . . 
. b 4 4 e e e e e e e e e b b . 
. 1 . 1 . 1 b b b b b b b e b . 
. . . . . . 1 b e e e e e e b . 
. . . . . . . b e e e e e e b . 
. . 3 3 . . 1 b e e e e e e b . 
. . . 3 3 . . b e e e e e e b . 
. 1 c 3 3 3 1 b e e e e e e b . 
. b 1 c 1 3 b e e e e e e e b . 
. b e e e e e e e e e e e e b . 
. b b b b b b b b b b b b b b . 
. . b . . . . . . . . . . b . . 
`, img`
. . . . . . . . . . . . . . . . 
. . b b b b b b b b b b b b . . 
. . b 4 4 e e e e e e e e b . . 
. b 4 4 e e e e e e e e e b b . 
. 1 . 1 . 1 b b b b b b b e b . 
. . . . . . 1 b e e e e e e b . 
. . . . . . . b e e e e e e b . 
. . . . . . 1 b e e e e e e b . 
. . . . . . . b e e e e e e b . 
3 3 3 3 . . 1 b e e e e e e b . 
. 3 3 3 3 . . b e e e e e e b . 
. 1 c 3 3 3 1 b e e e e e e b . 
. b 1 c 1 3 b e e e e e e e b . 
. b e e e e e e e e e e e e b . 
. b b b b b b b b b b b b b b . 
. . b . . . . . . . . . . b . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
